### ISSUE TITLE
Grade First Homework

### ISSUE THREAD

**Issue by zach-dethloff** [zach-dethloff/ASTR-119#5]
Would the TA's @tangyao1123 @ryarza please grade my first assignment?

**Comment by ryarza** [comment]
Hi @zach-dethloff,

You accepted the pull request and closed the issue manually. If you link the pull request to the issue, accepting the pull request will automatically close the issue. See for reference https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue
